spring.datasource.url=${DB_URL:jdbc:h2:mem:finpulse;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.show-sql=false
spring.h2.console.enabled=true
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/finpulse.p12
server.ssl.key-store-password=finpulse123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=finpulse
